name: React Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2 접속하여 작업
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script_stop: true
          script: |
            cd /home/ubuntu/feelog_client
            git pull origin main

            docker stop feelog_client || true
            docker rm feelog_client || true

            docker build --no-cache -t feelog_client .
            docker run -d --name feelog_client -p 80:80 feelog_client